// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: nfSxZjVucxtfieS23UFsqy
// Component: gy2erJa9TCe7Yo-
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Reviews from "../../Reviews"; // plasmic-import: c_QmF5P6dvy14Px/component
import AsFeaturedIn from "../../AsFeaturedIn"; // plasmic-import: pQTaPc4NQmA6IHD/component

import { useScreenVariants as useScreenVariantsrpLZvrBoo7PdKh } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: rpLZvrBoo_7pdKh/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_copy_of_blog_lifehacksplus_com.module.css"; // plasmic-import: nfSxZjVucxtfieS23UFsqy/projectcss
import sty from "./PlasmicBlog.module.css"; // plasmic-import: gy2erJa9TCe7Yo-/css

export type PlasmicBlog__VariantMembers = {};
export type PlasmicBlog__VariantsArgs = {};
type VariantPropType = keyof PlasmicBlog__VariantsArgs;
export const PlasmicBlog__VariantProps = new Array<VariantPropType>();

export type PlasmicBlog__ArgsType = {};
type ArgPropType = keyof PlasmicBlog__ArgsType;
export const PlasmicBlog__ArgProps = new Array<ArgPropType>();

export type PlasmicBlog__OverridesType = {
  root?: p.Flex<"div">;
  nav?: p.Flex<"div">;
  headline?: p.Flex<"div">;
  body?: p.Flex<"div">;
  asFeaturedIn?: p.Flex<typeof AsFeaturedIn>;
  link?: p.Flex<"a"> & Partial<LinkProps>;
  review1?: p.Flex<"div">;
  review2?: p.Flex<"div">;
  review3?: p.Flex<"div">;
  review4?: p.Flex<"div">;
};

export interface DefaultBlogProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicBlog__RenderFunc(props: {
  variants: PlasmicBlog__VariantsArgs;
  args: PlasmicBlog__ArgsType;
  overrides: PlasmicBlog__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsrpLZvrBoo7PdKh()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"nav"}
            data-plasmic-override={overrides.nav}
            className={classNames(projectcss.all, sty.nav)}
          >
            <div className={classNames(projectcss.all, sty.columns__efjM)}>
              <div className={classNames(projectcss.all, sty.column__crv5T)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__pkLVs)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/copy_of_blog_lifehacksplus_com/images/logopng.png",
                    fullWidth: 276,
                    fullHeight: 46,
                    aspectRatio: undefined
                  }}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__fvnsU)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eyLab
                  )}
                >
                  {'"The Evolution of Inhalation"'}
                </div>
              </div>
            </div>
          </div>

          <div
            data-plasmic-name={"headline"}
            data-plasmic-override={overrides.headline}
            className={classNames(projectcss.all, sty.headline)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__tNeXu
              )}
            >
              {"Hard Hitting Zero-Nic Pods Pack Intense Mango or Mint Flavor!"}
            </div>

            <button
              className={classNames(
                projectcss.all,
                projectcss.button,
                projectcss.__wab_text,
                sty.button__lzR70
              )}
              disabled={false}
              link={
                "https://www.quittinghacks.com/rechargeable-offer/" as const
              }
            >
              {"CLAIM FREE PODS 👉"}
            </button>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__yWmpv
              )}
            >
              <React.Fragment>
                <React.Fragment>
                  {"This new invention is turning \n"}
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"bad habits"}
                </span>
                <React.Fragment>{" into a "}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"healthy ones"}
                </span>
                <React.Fragment>{"..."}</React.Fragment>
              </React.Fragment>
            </div>

            <Reviews
              className={classNames("__wab_instance", sty.reviews__sSSbr)}
            />

            {true ? (
              <div className={classNames(projectcss.all, sty.columns__dda2U)}>
                <div className={classNames(projectcss.all, sty.column__yyyiO)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___6IpzF)}
                    displayHeight={"19px" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"none" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"123px" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/copy_of_blog_lifehacksplus_com/images/starpng2.png",
                      fullWidth: 142,
                      fullHeight: 21,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__eCvtA)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aIbp5
                    )}
                  >
                    {"Rated 4.9 Stars By 100,000+ Customers"}
                  </div>
                </div>
              </div>
            ) : null}
          </div>

          <div
            data-plasmic-name={"body"}
            data-plasmic-override={overrides.body}
            className={classNames(projectcss.all, sty.body)}
          >
            <AsFeaturedIn
              data-plasmic-name={"asFeaturedIn"}
              data-plasmic-override={overrides.asFeaturedIn}
              className={classNames("__wab_instance", sty.asFeaturedIn)}
            />

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__ixOxT)}
              displayHeight={"auto" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"100%" as const}
              link={
                "https://www.quittinghacks.com/rechargeable-offer/" as const
              }
              loading={"lazy" as const}
              src={{
                src: "/plasmic/copy_of_blog_lifehacksplus_com/images/_9B498Fb8RechargableGif11Gif.gif",
                fullWidth: 614,
                fullHeight: 332,
                aspectRatio: undefined
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__oe3DE
              )}
            >
              <React.Fragment>
                <React.Fragment>
                  {
                    "Imagine being nic-free but still getting that oh-so-satisfying throat hit along with delicious natural flavoring?\n\nIt almost sounds too good to be true, right? \n\nThe solution is simple... \n\nChoose natural ingredients, "
                  }
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"NOT"}
                </span>
                <React.Fragment>
                  {" Stimulants and Harmful Chemicals:"}
                </React.Fragment>
              </React.Fragment>
            </div>

            <p.PlasmicLink
              data-plasmic-name={"link"}
              data-plasmic-override={overrides.link}
              className={classNames(projectcss.all, projectcss.a, sty.link)}
              component={Link}
              href={
                "https://www.quittinghacks.com/rechargeable-offer/" as const
              }
              platform={"nextjs"}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__pd0SK)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100%" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_blog_lifehacksplus_com/images/screenshot20230224At43442PMpng.png",
                  fullWidth: 2352,
                  fullHeight: 802,
                  aspectRatio: undefined
                }}
              />
            </p.PlasmicLink>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__hTss
              )}
            >
              <React.Fragment>
                <React.Fragment>
                  {
                    "Sparq Zero® is the evolution of inhalation. \n\nOur revolutionary diffuser comes in your choice of natural Sweet Mango or natural Cool Mint, providing you with the throat hit and intense flavoring you’re looking for... "
                  }
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"without the guilt! "}
                </span>
                <React.Fragment>
                  {
                    "\n\nWe spent 6 years developing a device that was health-focused, lab-tested and that produced real throat hit and flavor that would effectively eliminate your cravings."
                  }
                </React.Fragment>
              </React.Fragment>
            </div>

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__wT3Np)}
              displayHeight={"auto" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"100%" as const}
              link={
                "https://www.quittinghacks.com/rechargeable-offer/" as const
              }
              loading={"lazy" as const}
              src={{
                src: "/plasmic/copy_of_blog_lifehacksplus_com/images/fbfd287ERechargableGif21Gif.gif",
                fullWidth: 614,
                fullHeight: 332,
                aspectRatio: undefined
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mpmtV
              )}
            >
              {
                "Absolutely no expense was spared with regard to design-form and function:\n\nThis ultra-modern metal device is slim, compact, odorless, and easy to use at any time or place."
              }
            </div>

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img___05UMo)}
              displayHeight={"auto" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"100%" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/copy_of_blog_lifehacksplus_com/images/_4B6E6Ed1Devicegif.gif",
                fullWidth: 669,
                fullHeight: 575,
                aspectRatio: undefined
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___6JbsB
              )}
            >
              <React.Fragment>
                <React.Fragment>
                  {
                    "Plus it comes it comes in your choice of two delicious flavors, Sweet Mango or Cool Mint!\n\nWe even offer a "
                  }
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"money-back guarantee"}
                </span>
                <React.Fragment>
                  {" if you don't absolutely love the taste and throat hit. "}
                </React.Fragment>
              </React.Fragment>
            </div>

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__n6HCt)}
              displayHeight={"auto" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"100%" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/copy_of_blog_lifehacksplus_com/images/_6Bb5E2F0Image31000000000000000000028Png.png",
                fullWidth: 614,
                fullHeight: 332,
                aspectRatio: undefined
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___1Y5Su
              )}
            >
              <React.Fragment>
                <React.Fragment>
                  {
                    "Most importantly, ALL of our formulations have undergone extensive lab-testing.\n\nThe test results verified our all-natural, plant-based pod ingredients are safe even when heated into a vapor.\n\n"
                  }
                </React.Fragment>
                {
                  <ul
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__kg1LY
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__snjFk
                      )}
                    >
                      {
                        "no harmful byproducts produced during the heating process (Gas chromatography)"
                      }
                    </li>
                  </ul>
                }
                <React.Fragment>{"\n"}</React.Fragment>
                {
                  <ul
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul___0SyQ2
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__w9FZs
                      )}
                    >
                      {"no evidence of carbonyl compounds"}
                    </li>
                  </ul>
                }
                <React.Fragment>{"\n"}</React.Fragment>
                {
                  <ul
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__vu7J
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li___5KDxo
                      )}
                    >
                      {
                        "no evidence of “bad characters” known in the industry, including Diacetyl, Acrolein and Acetoin"
                      }
                    </li>
                  </ul>
                }
                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </div>

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__znZwu)}
              displayHeight={"auto" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"100%" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/copy_of_blog_lifehacksplus_com/images/_12A7A7BbTestingSmallerImage10Yy0Fa0000000000000281Png.png",
                fullWidth: 1258,
                fullHeight: 550,
                aspectRatio: undefined
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__xh5Gf
              )}
            >
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"Figure 1:"}
                </span>
                <React.Fragment>
                  {
                    " ISO-Accredited Laboratory certified safety and ensured the liquid remains stable even when heated."
                  }
                </React.Fragment>
              </React.Fragment>
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__vSu3Q
              )}
            >
              <React.Fragment>
                <React.Fragment>
                  {
                    "We are incredibly proud to state that we have helped over 100,000 people quit while still allowing them to enjoy their habit, without any guilt!\n\nWe’ve made it easy for you to do the same, by offering a "
                  }
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"FREE"}
                </span>
                <React.Fragment>
                  {
                    " box of our Sweet Mango or Cool Mint pods, with your first purchase, auto-applied at checkout."
                  }
                </React.Fragment>
              </React.Fragment>
            </div>

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img___2WU0)}
              displayHeight={"auto" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"100%" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/copy_of_blog_lifehacksplus_com/images/_7048E521Hit110000000000000000000281Png.png",
                fullWidth: 614,
                fullHeight: 332,
                aspectRatio: undefined
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__q02PE
              )}
            >
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"Click Here to Claim Free Sweet Mango or Cool Mint Pods!"}
                </span>
              </React.Fragment>
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__eWrTz
              )}
            >
              {"Fast Same Day Shipping"}
            </div>

            <div className={classNames(projectcss.all, sty.columns___49FTe)}>
              <div className={classNames(projectcss.all, sty.column___9IHfy)}>
                <button
                  className={classNames(
                    projectcss.all,
                    projectcss.button,
                    projectcss.__wab_text,
                    sty.button__fq9D
                  )}
                >
                  {"CLAIM FREE PODS 👉"}
                </button>
              </div>

              <div className={classNames(projectcss.all, sty.column__c4Hpo)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___14AtL)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/copy_of_blog_lifehacksplus_com/images/dividersvg.bin",
                    fullWidth: 5,
                    fullHeight: 150,
                    aspectRatio: 0.033333
                  }}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__jSkwn)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cEmi
                  )}
                >
                  {"100,000+ Happy Customers! In Stock - Ships Now."}
                </div>

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___0Y9Bn)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/copy_of_blog_lifehacksplus_com/images/starpng2.png",
                    fullWidth: 142,
                    fullHeight: 21,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__q6BF1)}
              displayHeight={"auto" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"100%" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/copy_of_blog_lifehacksplus_com/images/silverDeviceOutrogif.gif",
                fullWidth: 669,
                fullHeight: 575,
                aspectRatio: undefined
              }}
            />
          </div>

          <div className={classNames(projectcss.all, sty.freeBox___1G8N)}>
            <div
              data-plasmic-name={"review1"}
              data-plasmic-override={overrides.review1}
              className={classNames(projectcss.all, sty.review1)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img___2Pmu4)}
                displayHeight={"100px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_blog_lifehacksplus_com/images/sidereview1Png.png",
                  fullWidth: 119,
                  fullHeight: 119,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__c6Gmo
                )}
              >
                {"Isaiah S."}
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__jkNy1)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"auto" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_blog_lifehacksplus_com/images/starpng2.png",
                  fullWidth: 142,
                  fullHeight: 21,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__kz6Q
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"BEST ALTERNATIVE"}
                  </span>
                </React.Fragment>
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___40TxJ
                )}
              >
                {
                  '"I smoked for 12 years and tried to quit several times with no success. Until I came across Vitamin Air. Now not only do I not smoke, I’m doing something healthy in place! Great product, I’ll be a user for life!"'
                }
              </div>
            </div>

            <div
              data-plasmic-name={"review2"}
              data-plasmic-override={overrides.review2}
              className={classNames(projectcss.all, sty.review2)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img___8MUe1)}
                displayHeight={"100px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_blog_lifehacksplus_com/images/sidereview2Png.png",
                  fullWidth: 119,
                  fullHeight: 119,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zMpIa
                )}
              >
                {"Jason G."}
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__s3EuV)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"auto" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_blog_lifehacksplus_com/images/starpng2.png",
                  fullWidth: 142,
                  fullHeight: 21,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qCpDi
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"AWESOME"}
                  </span>
                </React.Fragment>
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mftpi
                )}
              >
                {
                  "“Excellent. I love this. I quit cigs and went to the sparq. I love this device. It is natural, no nic. It really does help calm me.”"
                }
              </div>
            </div>

            <div
              data-plasmic-name={"review3"}
              data-plasmic-override={overrides.review3}
              className={classNames(projectcss.all, sty.review3)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__cHf6V)}
                displayHeight={"100px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_blog_lifehacksplus_com/images/sidereview3Png.png",
                  fullWidth: 119,
                  fullHeight: 119,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qAtK0
                )}
              >
                {"Kathy B"}
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__jeSi9)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"auto" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_blog_lifehacksplus_com/images/starpng2.png",
                  fullWidth: 142,
                  fullHeight: 21,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__lfTw
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"LOVE! LOVE!!"}
                  </span>
                </React.Fragment>
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__drFeY
                )}
              >
                {
                  "“Im literally obsessed the the elegant\ndesign as well as the jaw dropping\npackaging.”"
                }
              </div>
            </div>

            <div
              data-plasmic-name={"review4"}
              data-plasmic-override={overrides.review4}
              className={classNames(projectcss.all, sty.review4)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__uIe4U)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_blog_lifehacksplus_com/images/starpng2.png",
                  fullWidth: 142,
                  fullHeight: 21,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fisjX
                )}
              >
                <React.Fragment>
                  <React.Fragment>{"Rated 4.9 Stars By "}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"100,000+"}
                  </span>
                  <React.Fragment>{" Customers"}</React.Fragment>
                </React.Fragment>
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dzMzS
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"So What Are You Waiting For?"}
                  </span>
                </React.Fragment>
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__k5Gmx
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700, color: "#FFFFFF" }}
                  >
                    {
                      "Order today and receive a FREE Box of Pods or a Disposable Device!"
                    }
                  </span>
                </React.Fragment>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "nav",
    "headline",
    "body",
    "asFeaturedIn",
    "link",
    "review1",
    "review2",
    "review3",
    "review4"
  ],
  nav: ["nav"],
  headline: ["headline"],
  body: ["body", "asFeaturedIn", "link"],
  asFeaturedIn: ["asFeaturedIn"],
  link: ["link"],
  review1: ["review1"],
  review2: ["review2"],
  review3: ["review3"],
  review4: ["review4"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  nav: "div";
  headline: "div";
  body: "div";
  asFeaturedIn: typeof AsFeaturedIn;
  link: "a";
  review1: "div";
  review2: "div";
  review3: "div";
  review4: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBlog__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBlog__VariantsArgs;
    args?: PlasmicBlog__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBlog__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicBlog__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicBlog__ArgProps,
          internalVariantPropNames: PlasmicBlog__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicBlog__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBlog";
  } else {
    func.displayName = `PlasmicBlog.${nodeName}`;
  }
  return func;
}

export const PlasmicBlog = Object.assign(
  // Top-level PlasmicBlog renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    nav: makeNodeComponent("nav"),
    headline: makeNodeComponent("headline"),
    body: makeNodeComponent("body"),
    asFeaturedIn: makeNodeComponent("asFeaturedIn"),
    link: makeNodeComponent("link"),
    review1: makeNodeComponent("review1"),
    review2: makeNodeComponent("review2"),
    review3: makeNodeComponent("review3"),
    review4: makeNodeComponent("review4"),

    // Metadata about props expected for PlasmicBlog
    internalVariantProps: PlasmicBlog__VariantProps,
    internalArgProps: PlasmicBlog__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicBlog;
/* prettier-ignore-end */
