// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wJD4VsJTYW6gZPn3AUEzqs
// Component: H9F42oltm8Qyu
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import _320PxFooter from "../../_320PxFooter"; // plasmic-import: uG3j3zIrAJz3e/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_masteri_sparq.module.css"; // plasmic-import: wJD4VsJTYW6gZPn3AUEzqs/projectcss
import sty from "./Plasmic_320PxFooterI.module.css"; // plasmic-import: H9F42oltm8Qyu/css

export type Plasmic_320PxFooterI__VariantMembers = {};
export type Plasmic_320PxFooterI__VariantsArgs = {};
type VariantPropType = keyof Plasmic_320PxFooterI__VariantsArgs;
export const Plasmic_320PxFooterI__VariantProps = new Array<VariantPropType>();

export type Plasmic_320PxFooterI__ArgsType = {};
type ArgPropType = keyof Plasmic_320PxFooterI__ArgsType;
export const Plasmic_320PxFooterI__ArgProps = new Array<ArgPropType>();

export type Plasmic_320PxFooterI__OverridesType = {
  divshopifySectionFooter3?: p.Flex<"div">;
  _320PxFooter?: p.Flex<typeof _320PxFooter>;
};

export interface Default_320PxFooterIProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function Plasmic_320PxFooterI__RenderFunc(props: {
  variants: Plasmic_320PxFooterI__VariantsArgs;
  args: Plasmic_320PxFooterI__ArgsType;
  overrides: Plasmic_320PxFooterI__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  return (
    <div
      data-plasmic-name={"divshopifySectionFooter3"}
      data-plasmic-override={overrides.divshopifySectionFooter3}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.divshopifySectionFooter3
      )}
    >
      <_320PxFooter
        data-plasmic-name={"_320PxFooter"}
        data-plasmic-override={overrides._320PxFooter}
        className={classNames("__wab_instance", sty._320PxFooter)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  divshopifySectionFooter3: ["divshopifySectionFooter3", "_320PxFooter"],
  _320PxFooter: ["_320PxFooter"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  divshopifySectionFooter3: "div";
  _320PxFooter: typeof _320PxFooter;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  Plasmic_320PxFooterI__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: Plasmic_320PxFooterI__VariantsArgs;
    args?: Plasmic_320PxFooterI__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<Plasmic_320PxFooterI__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      Plasmic_320PxFooterI__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: Plasmic_320PxFooterI__ArgProps,
          internalVariantPropNames: Plasmic_320PxFooterI__VariantProps
        }),
      [props, nodeName]
    );
    return Plasmic_320PxFooterI__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "divshopifySectionFooter3") {
    func.displayName = "Plasmic_320PxFooterI";
  } else {
    func.displayName = `Plasmic_320PxFooterI.${nodeName}`;
  }
  return func;
}

export const Plasmic_320PxFooterI = Object.assign(
  // Top-level Plasmic_320PxFooterI renders the root element
  makeNodeComponent("divshopifySectionFooter3"),
  {
    // Helper components rendering sub-elements
    _320PxFooter: makeNodeComponent("_320PxFooter"),

    // Metadata about props expected for Plasmic_320PxFooterI
    internalVariantProps: Plasmic_320PxFooterI__VariantProps,
    internalArgProps: Plasmic_320PxFooterI__ArgProps
  }
);

export default Plasmic_320PxFooterI;
/* prettier-ignore-end */
