// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wJD4VsJTYW6gZPn3AUEzqs
// Component: 4Xmgn6n080BCX
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_masteri_sparq.module.css"; // plasmic-import: wJD4VsJTYW6gZPn3AUEzqs/projectcss
import sty from "./Plasmic_1440VarietyRedo.module.css"; // plasmic-import: 4Xmgn6n080BCX/css

export type Plasmic_1440VarietyRedo__VariantMembers = {};
export type Plasmic_1440VarietyRedo__VariantsArgs = {};
type VariantPropType = keyof Plasmic_1440VarietyRedo__VariantsArgs;
export const Plasmic_1440VarietyRedo__VariantProps =
  new Array<VariantPropType>();

export type Plasmic_1440VarietyRedo__ArgsType = {};
type ArgPropType = keyof Plasmic_1440VarietyRedo__ArgsType;
export const Plasmic_1440VarietyRedo__ArgProps = new Array<ArgPropType>();

export type Plasmic_1440VarietyRedo__OverridesType = {
  div122?: p.Flex<"div">;
  a13?: p.Flex<"div">;
  packaging6Upright09FinalMin250X2502Xjpg2?: p.Flex<"a"> & Partial<LinkProps>;
  div123?: p.Flex<"div">;
  _43Rating447Votes10?: p.Flex<"div">;
  i46?: p.Flex<"div">;
  i47?: p.Flex<"div">;
  i48?: p.Flex<"div">;
  i49?: p.Flex<"div">;
  i50?: p.Flex<"div">;
  div124?: p.Flex<"a"> & Partial<LinkProps>;
  span8?: p.Flex<"div">;
  bestValue2?: p.Flex<"div">;
  form10?: p.Flex<"div">;
  div125?: p.Flex<"div">;
  div126?: p.Flex<"div">;
  div127?: p.Flex<"a"> & Partial<LinkProps>;
  label19?: p.Flex<"div">;
  strawberry10?: p.Flex<"div">;
  div128?: p.Flex<"a"> & Partial<LinkProps>;
  label20?: p.Flex<"div">;
  vanilla10?: p.Flex<"div">;
  div129?: p.Flex<"div">;
  buttonAddToCart43324429107892?: p.Flex<"a"> & Partial<LinkProps>;
};

export interface Default_1440VarietyRedoProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function Plasmic_1440VarietyRedo__RenderFunc(props: {
  variants: Plasmic_1440VarietyRedo__VariantsArgs;
  args: Plasmic_1440VarietyRedo__ArgsType;
  overrides: Plasmic_1440VarietyRedo__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  return (
    <div
      data-plasmic-name={"div122"}
      data-plasmic-override={overrides.div122}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.div122
      )}
    >
      <div
        data-plasmic-name={"a13"}
        data-plasmic-override={overrides.a13}
        className={classNames(projectcss.all, sty.a13)}
      >
        <p.PlasmicLink
          data-plasmic-name={"packaging6Upright09FinalMin250X2502Xjpg2"}
          data-plasmic-override={
            overrides.packaging6Upright09FinalMin250X2502Xjpg2
          }
          className={classNames(
            projectcss.all,
            projectcss.a,
            sty.packaging6Upright09FinalMin250X2502Xjpg2
          )}
          component={Link}
          href={
            "https://shop.lifehacksplus.com/discount/QUIT15?redirect=/collections/all/products/variety-pack" as const
          }
          platform={"nextjs"}
        />

        <div
          data-plasmic-name={"div123"}
          data-plasmic-override={overrides.div123}
          className={classNames(projectcss.all, sty.div123)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__cgIa9
            )}
          >
            {"Variety Pack"}
          </div>

          <div
            data-plasmic-name={"_43Rating447Votes10"}
            data-plasmic-override={overrides._43Rating447Votes10}
            className={classNames(projectcss.all, sty._43Rating447Votes10)}
          >
            <div
              data-plasmic-name={"i46"}
              data-plasmic-override={overrides.i46}
              className={classNames(projectcss.all, sty.i46)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wdiSi
                )}
              >
                {"★\t"}
              </div>
            </div>

            <div
              data-plasmic-name={"i47"}
              data-plasmic-override={overrides.i47}
              className={classNames(projectcss.all, sty.i47)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__feQ9U
                )}
              >
                {"★\t"}
              </div>
            </div>

            <div
              data-plasmic-name={"i48"}
              data-plasmic-override={overrides.i48}
              className={classNames(projectcss.all, sty.i48)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__yIrIw
                )}
              >
                {"★\t"}
              </div>
            </div>

            <div
              data-plasmic-name={"i49"}
              data-plasmic-override={overrides.i49}
              className={classNames(projectcss.all, sty.i49)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__reQF
                )}
              >
                {"★\t"}
              </div>
            </div>

            <div
              data-plasmic-name={"i50"}
              data-plasmic-override={overrides.i50}
              className={classNames(projectcss.all, sty.i50)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hThC
                )}
              >
                {"★\t"}
              </div>
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__fwOPh
              )}
            >
              {"(447)"}
            </div>
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__blwzh
            )}
          >
            {"$98 + FREE SHIPPING"}
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__zdseu
            )}
          >
            {"(One of each formulation in both flavors)"}
          </div>
        </div>

        <p.PlasmicLink
          data-plasmic-name={"div124"}
          data-plasmic-override={overrides.div124}
          className={classNames(projectcss.all, projectcss.a, sty.div124)}
          component={Link}
          href={
            "https://shop.lifehacksplus.com/discount/QUIT15?redirect=/collections/all/products/variety-pack" as const
          }
          platform={"nextjs"}
        >
          <div
            data-plasmic-name={"span8"}
            data-plasmic-override={overrides.span8}
            className={classNames(projectcss.all, sty.span8)}
          >
            <div
              data-plasmic-name={"bestValue2"}
              data-plasmic-override={overrides.bestValue2}
              className={classNames(projectcss.all, sty.bestValue2)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__rhGhx
              )}
            >
              {"BEST VALUE!"}
            </div>
          </div>
        </p.PlasmicLink>
      </div>

      <div
        data-plasmic-name={"form10"}
        data-plasmic-override={overrides.form10}
        className={classNames(projectcss.all, sty.form10)}
      >
        <div
          data-plasmic-name={"div125"}
          data-plasmic-override={overrides.div125}
          className={classNames(projectcss.all, sty.div125)}
        >
          <div
            data-plasmic-name={"div126"}
            data-plasmic-override={overrides.div126}
            className={classNames(projectcss.all, sty.div126)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__kBetZ
              )}
            >
              {"Contains Both:"}
            </div>

            <p.PlasmicLink
              data-plasmic-name={"div127"}
              data-plasmic-override={overrides.div127}
              className={classNames(projectcss.all, projectcss.a, sty.div127)}
              component={Link}
              href={
                "https://shop.lifehacksplus.com/discount/QUIT15?redirect=/collections/all/products/variety-pack" as const
              }
              platform={"nextjs"}
            >
              <div
                data-plasmic-name={"label19"}
                data-plasmic-override={overrides.label19}
                className={classNames(projectcss.all, sty.label19)}
              />

              <div
                data-plasmic-name={"strawberry10"}
                data-plasmic-override={overrides.strawberry10}
                className={classNames(projectcss.all, sty.strawberry10)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tgLyS
                  )}
                >
                  {"Strawberry"}
                </div>
              </div>
            </p.PlasmicLink>

            <p.PlasmicLink
              data-plasmic-name={"div128"}
              data-plasmic-override={overrides.div128}
              className={classNames(projectcss.all, projectcss.a, sty.div128)}
              component={Link}
              href={
                "https://shop.lifehacksplus.com/discount/QUIT15?redirect=/collections/all/products/variety-pack" as const
              }
              platform={"nextjs"}
            >
              <div
                data-plasmic-name={"label20"}
                data-plasmic-override={overrides.label20}
                className={classNames(projectcss.all, sty.label20)}
              />

              <div
                data-plasmic-name={"vanilla10"}
                data-plasmic-override={overrides.vanilla10}
                className={classNames(projectcss.all, sty.vanilla10)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cUwCb
                  )}
                >
                  {"Vanilla"}
                </div>
              </div>
            </p.PlasmicLink>
          </div>
        </div>

        <div
          data-plasmic-name={"div129"}
          data-plasmic-override={overrides.div129}
          className={classNames(projectcss.all, sty.div129)}
        >
          <p.PlasmicLink
            data-plasmic-name={"buttonAddToCart43324429107892"}
            data-plasmic-override={overrides.buttonAddToCart43324429107892}
            className={classNames(
              projectcss.all,
              projectcss.a,
              sty.buttonAddToCart43324429107892
            )}
            component={Link}
            href={
              "https://shop.lifehacksplus.com/discount/QUIT15?redirect=/collections/all/products/variety-pack" as const
            }
            platform={"nextjs"}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__idA45
              )}
            >
              {"SHOP NOW"}
            </div>
          </p.PlasmicLink>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  div122: [
    "div122",
    "a13",
    "packaging6Upright09FinalMin250X2502Xjpg2",
    "div123",
    "_43Rating447Votes10",
    "i46",
    "i47",
    "i48",
    "i49",
    "i50",
    "div124",
    "span8",
    "bestValue2",
    "form10",
    "div125",
    "div126",
    "div127",
    "label19",
    "strawberry10",
    "div128",
    "label20",
    "vanilla10",
    "div129",
    "buttonAddToCart43324429107892"
  ],
  a13: [
    "a13",
    "packaging6Upright09FinalMin250X2502Xjpg2",
    "div123",
    "_43Rating447Votes10",
    "i46",
    "i47",
    "i48",
    "i49",
    "i50",
    "div124",
    "span8",
    "bestValue2"
  ],
  packaging6Upright09FinalMin250X2502Xjpg2: [
    "packaging6Upright09FinalMin250X2502Xjpg2"
  ],
  div123: ["div123", "_43Rating447Votes10", "i46", "i47", "i48", "i49", "i50"],
  _43Rating447Votes10: [
    "_43Rating447Votes10",
    "i46",
    "i47",
    "i48",
    "i49",
    "i50"
  ],
  i46: ["i46"],
  i47: ["i47"],
  i48: ["i48"],
  i49: ["i49"],
  i50: ["i50"],
  div124: ["div124", "span8", "bestValue2"],
  span8: ["span8", "bestValue2"],
  bestValue2: ["bestValue2"],
  form10: [
    "form10",
    "div125",
    "div126",
    "div127",
    "label19",
    "strawberry10",
    "div128",
    "label20",
    "vanilla10",
    "div129",
    "buttonAddToCart43324429107892"
  ],
  div125: [
    "div125",
    "div126",
    "div127",
    "label19",
    "strawberry10",
    "div128",
    "label20",
    "vanilla10"
  ],
  div126: [
    "div126",
    "div127",
    "label19",
    "strawberry10",
    "div128",
    "label20",
    "vanilla10"
  ],
  div127: ["div127", "label19", "strawberry10"],
  label19: ["label19"],
  strawberry10: ["strawberry10"],
  div128: ["div128", "label20", "vanilla10"],
  label20: ["label20"],
  vanilla10: ["vanilla10"],
  div129: ["div129", "buttonAddToCart43324429107892"],
  buttonAddToCart43324429107892: ["buttonAddToCart43324429107892"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  div122: "div";
  a13: "div";
  packaging6Upright09FinalMin250X2502Xjpg2: "a";
  div123: "div";
  _43Rating447Votes10: "div";
  i46: "div";
  i47: "div";
  i48: "div";
  i49: "div";
  i50: "div";
  div124: "a";
  span8: "div";
  bestValue2: "div";
  form10: "div";
  div125: "div";
  div126: "div";
  div127: "a";
  label19: "div";
  strawberry10: "div";
  div128: "a";
  label20: "div";
  vanilla10: "div";
  div129: "div";
  buttonAddToCart43324429107892: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  Plasmic_1440VarietyRedo__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: Plasmic_1440VarietyRedo__VariantsArgs;
    args?: Plasmic_1440VarietyRedo__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<Plasmic_1440VarietyRedo__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      Plasmic_1440VarietyRedo__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: Plasmic_1440VarietyRedo__ArgProps,
          internalVariantPropNames: Plasmic_1440VarietyRedo__VariantProps
        }),
      [props, nodeName]
    );
    return Plasmic_1440VarietyRedo__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "div122") {
    func.displayName = "Plasmic_1440VarietyRedo";
  } else {
    func.displayName = `Plasmic_1440VarietyRedo.${nodeName}`;
  }
  return func;
}

export const Plasmic_1440VarietyRedo = Object.assign(
  // Top-level Plasmic_1440VarietyRedo renders the root element
  makeNodeComponent("div122"),
  {
    // Helper components rendering sub-elements
    a13: makeNodeComponent("a13"),
    packaging6Upright09FinalMin250X2502Xjpg2: makeNodeComponent(
      "packaging6Upright09FinalMin250X2502Xjpg2"
    ),
    div123: makeNodeComponent("div123"),
    _43Rating447Votes10: makeNodeComponent("_43Rating447Votes10"),
    i46: makeNodeComponent("i46"),
    i47: makeNodeComponent("i47"),
    i48: makeNodeComponent("i48"),
    i49: makeNodeComponent("i49"),
    i50: makeNodeComponent("i50"),
    div124: makeNodeComponent("div124"),
    span8: makeNodeComponent("span8"),
    bestValue2: makeNodeComponent("bestValue2"),
    form10: makeNodeComponent("form10"),
    div125: makeNodeComponent("div125"),
    div126: makeNodeComponent("div126"),
    div127: makeNodeComponent("div127"),
    label19: makeNodeComponent("label19"),
    strawberry10: makeNodeComponent("strawberry10"),
    div128: makeNodeComponent("div128"),
    label20: makeNodeComponent("label20"),
    vanilla10: makeNodeComponent("vanilla10"),
    div129: makeNodeComponent("div129"),
    buttonAddToCart43324429107892: makeNodeComponent(
      "buttonAddToCart43324429107892"
    ),

    // Metadata about props expected for Plasmic_1440VarietyRedo
    internalVariantProps: Plasmic_1440VarietyRedo__VariantProps,
    internalArgProps: Plasmic_1440VarietyRedo__ArgProps
  }
);

export default Plasmic_1440VarietyRedo;
/* prettier-ignore-end */
