// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wJD4VsJTYW6gZPn3AUEzqs
// Component: 1N7tS9KuyaeeL
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_masteri_sparq.module.css"; // plasmic-import: wJD4VsJTYW6gZPn3AUEzqs/projectcss
import sty from "./PlasmicFooter414Px.module.css"; // plasmic-import: 1N7tS9KuyaeeL/css

import FrameIcon from "./icons/PlasmicIcon__Frame"; // plasmic-import: dKOnOogHBbFBR/icon
import Frame2Icon from "./icons/PlasmicIcon__Frame2"; // plasmic-import: TMewibysxbmq5/icon
import Frame3Icon from "./icons/PlasmicIcon__Frame3"; // plasmic-import: 3vPoGyuPi5l3b/icon

export type PlasmicFooter414Px__VariantMembers = {};
export type PlasmicFooter414Px__VariantsArgs = {};
type VariantPropType = keyof PlasmicFooter414Px__VariantsArgs;
export const PlasmicFooter414Px__VariantProps = new Array<VariantPropType>();

export type PlasmicFooter414Px__ArgsType = {};
type ArgPropType = keyof PlasmicFooter414Px__ArgsType;
export const PlasmicFooter414Px__ArgProps = new Array<ArgPropType>();

export type PlasmicFooter414Px__OverridesType = {
  divshopifySectionFooter?: p.Flex<"div">;
  div62?: p.Flex<"div">;
  footerLogopng?: p.Flex<"a"> & Partial<LinkProps>;
  div63?: p.Flex<"div">;
  div64?: p.Flex<"div">;
  div65?: p.Flex<"div">;
  company?: p.Flex<"div">;
  ul?: p.Flex<"div">;
  about?: p.Flex<"div">;
  press?: p.Flex<"div">;
  howItWorks?: p.Flex<"div">;
  contact?: p.Flex<"div">;
  brandAmbassador?: p.Flex<"div">;
  becomeASeller?: p.Flex<"div">;
  philosophy?: p.Flex<"div">;
  philanthropy?: p.Flex<"div">;
  helpFaQs?: p.Flex<"div">;
  div66?: p.Flex<"div">;
  products?: p.Flex<"div">;
  ul2?: p.Flex<"div">;
  rechargeable?: p.Flex<"div">;
  disposable?: p.Flex<"div">;
  giftCards?: p.Flex<"div">;
  div67?: p.Flex<"div">;
  legal?: p.Flex<"div">;
  ul3?: p.Flex<"div">;
  termsOfUse?: p.Flex<"div">;
  privacyPolicy?: p.Flex<"div">;
  shipping?: p.Flex<"div">;
  returnPolicy?: p.Flex<"div">;
  warranty?: p.Flex<"div">;
  div68?: p.Flex<"div">;
  div69?: p.Flex<"div">;
  followUs?: p.Flex<"div">;
  ul4?: p.Flex<"div">;
  svg2?: p.Flex<"div">;
  svg3?: p.Flex<"div">;
  shopifySecureBadgeLightShadowpng?: p.Flex<"div">;
};

export interface DefaultFooter414PxProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFooter414Px__RenderFunc(props: {
  variants: PlasmicFooter414Px__VariantsArgs;
  args: PlasmicFooter414Px__ArgsType;
  overrides: PlasmicFooter414Px__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  return (
    <div
      data-plasmic-name={"divshopifySectionFooter"}
      data-plasmic-override={overrides.divshopifySectionFooter}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.divshopifySectionFooter
      )}
    >
      <div
        data-plasmic-name={"div62"}
        data-plasmic-override={overrides.div62}
        className={classNames(projectcss.all, sty.div62)}
      >
        <p.PlasmicLink
          data-plasmic-name={"footerLogopng"}
          data-plasmic-override={overrides.footerLogopng}
          className={classNames(
            projectcss.all,
            projectcss.a,
            sty.footerLogopng
          )}
          component={Link}
          href={"https://shop.lifehacksplus.com/discount/QUIT15" as const}
          platform={"nextjs"}
        />

        <div
          data-plasmic-name={"div63"}
          data-plasmic-override={overrides.div63}
          className={classNames(projectcss.all, sty.div63)}
        >
          <div
            data-plasmic-name={"div64"}
            data-plasmic-override={overrides.div64}
            className={classNames(projectcss.all, sty.div64)}
          >
            <div
              data-plasmic-name={"div65"}
              data-plasmic-override={overrides.div65}
              className={classNames(projectcss.all, sty.div65)}
            >
              <div
                data-plasmic-name={"company"}
                data-plasmic-override={overrides.company}
                className={classNames(projectcss.all, sty.company)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5CYiJ
                  )}
                >
                  {"Company"}
                </div>
              </div>

              <div
                data-plasmic-name={"ul"}
                data-plasmic-override={overrides.ul}
                className={classNames(projectcss.all, sty.ul)}
              >
                <div
                  data-plasmic-name={"about"}
                  data-plasmic-override={overrides.about}
                  className={classNames(projectcss.all, sty.about)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__npeXw
                    )}
                  >
                    {"About"}
                  </div>
                </div>

                <div
                  data-plasmic-name={"press"}
                  data-plasmic-override={overrides.press}
                  className={classNames(projectcss.all, sty.press)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tbI3X
                    )}
                  >
                    {"Press"}
                  </div>
                </div>

                <div
                  data-plasmic-name={"howItWorks"}
                  data-plasmic-override={overrides.howItWorks}
                  className={classNames(projectcss.all, sty.howItWorks)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7Zrkl
                    )}
                  >
                    {"How it works"}
                  </div>
                </div>

                <div
                  data-plasmic-name={"contact"}
                  data-plasmic-override={overrides.contact}
                  className={classNames(projectcss.all, sty.contact)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aQ2DM
                    )}
                  >
                    {"Contact"}
                  </div>
                </div>

                <div
                  data-plasmic-name={"brandAmbassador"}
                  data-plasmic-override={overrides.brandAmbassador}
                  className={classNames(projectcss.all, sty.brandAmbassador)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pL1T
                    )}
                  >
                    {"Brand Ambassador"}
                  </div>
                </div>

                <div
                  data-plasmic-name={"becomeASeller"}
                  data-plasmic-override={overrides.becomeASeller}
                  className={classNames(projectcss.all, sty.becomeASeller)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3B8Pk
                    )}
                  >
                    {"Become a seller"}
                  </div>
                </div>

                <div
                  data-plasmic-name={"philosophy"}
                  data-plasmic-override={overrides.philosophy}
                  className={classNames(projectcss.all, sty.philosophy)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8QuP4
                    )}
                  >
                    {"Philosophy"}
                  </div>
                </div>

                <div
                  data-plasmic-name={"philanthropy"}
                  data-plasmic-override={overrides.philanthropy}
                  className={classNames(projectcss.all, sty.philanthropy)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pR768
                    )}
                  >
                    {"Philanthropy"}
                  </div>
                </div>

                <div
                  data-plasmic-name={"helpFaQs"}
                  data-plasmic-override={overrides.helpFaQs}
                  className={classNames(projectcss.all, sty.helpFaQs)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0F4EF
                    )}
                  >
                    {"Help/FAQs"}
                  </div>
                </div>
              </div>
            </div>

            <div
              data-plasmic-name={"div66"}
              data-plasmic-override={overrides.div66}
              className={classNames(projectcss.all, sty.div66)}
            >
              <div
                data-plasmic-name={"products"}
                data-plasmic-override={overrides.products}
                className={classNames(projectcss.all, sty.products)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zcPx
                  )}
                >
                  {"Products"}
                </div>
              </div>

              <div
                data-plasmic-name={"ul2"}
                data-plasmic-override={overrides.ul2}
                className={classNames(projectcss.all, sty.ul2)}
              >
                <div
                  data-plasmic-name={"rechargeable"}
                  data-plasmic-override={overrides.rechargeable}
                  className={classNames(projectcss.all, sty.rechargeable)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ldikS
                    )}
                  >
                    {"Rechargeable"}
                  </div>
                </div>

                <div
                  data-plasmic-name={"disposable"}
                  data-plasmic-override={overrides.disposable}
                  className={classNames(projectcss.all, sty.disposable)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__svWzi
                    )}
                  >
                    {"Disposable"}
                  </div>
                </div>

                <div
                  data-plasmic-name={"giftCards"}
                  data-plasmic-override={overrides.giftCards}
                  className={classNames(projectcss.all, sty.giftCards)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nIfQ9
                    )}
                  >
                    {"Gift Cards"}
                  </div>
                </div>
              </div>
            </div>

            <div
              data-plasmic-name={"div67"}
              data-plasmic-override={overrides.div67}
              className={classNames(projectcss.all, sty.div67)}
            >
              <div
                data-plasmic-name={"legal"}
                data-plasmic-override={overrides.legal}
                className={classNames(projectcss.all, sty.legal)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__b2Ndt
                  )}
                >
                  {"Legal"}
                </div>
              </div>

              <div
                data-plasmic-name={"ul3"}
                data-plasmic-override={overrides.ul3}
                className={classNames(projectcss.all, sty.ul3)}
              >
                <div
                  data-plasmic-name={"termsOfUse"}
                  data-plasmic-override={overrides.termsOfUse}
                  className={classNames(projectcss.all, sty.termsOfUse)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__p5Eai
                    )}
                  >
                    {"Terms of use"}
                  </div>
                </div>

                <div
                  data-plasmic-name={"privacyPolicy"}
                  data-plasmic-override={overrides.privacyPolicy}
                  className={classNames(projectcss.all, sty.privacyPolicy)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sgjPg
                    )}
                  >
                    {"Privacy Policy"}
                  </div>
                </div>

                <div
                  data-plasmic-name={"shipping"}
                  data-plasmic-override={overrides.shipping}
                  className={classNames(projectcss.all, sty.shipping)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__waHVm
                    )}
                  >
                    {"Shipping"}
                  </div>
                </div>

                <div
                  data-plasmic-name={"returnPolicy"}
                  data-plasmic-override={overrides.returnPolicy}
                  className={classNames(projectcss.all, sty.returnPolicy)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lvnUj
                    )}
                  >
                    {"Return Policy"}
                  </div>
                </div>

                <div
                  data-plasmic-name={"warranty"}
                  data-plasmic-override={overrides.warranty}
                  className={classNames(projectcss.all, sty.warranty)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7MaeV
                    )}
                  >
                    {"Warranty"}
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div
            data-plasmic-name={"div68"}
            data-plasmic-override={overrides.div68}
            className={classNames(projectcss.all, sty.div68)}
          >
            <div
              data-plasmic-name={"div69"}
              data-plasmic-override={overrides.div69}
              className={classNames(projectcss.all, sty.div69)}
            >
              <div
                data-plasmic-name={"followUs"}
                data-plasmic-override={overrides.followUs}
                className={classNames(projectcss.all, sty.followUs)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__puQ8U
                  )}
                >
                  {"Follow US"}
                </div>
              </div>

              <div
                data-plasmic-name={"ul4"}
                data-plasmic-override={overrides.ul4}
                className={classNames(projectcss.all, sty.ul4)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__hxGim)}>
                  <FrameIcon
                    className={classNames(projectcss.all, sty.svg__mUeWr)}
                    role={"img"}
                  />
                </div>

                <div
                  data-plasmic-name={"svg2"}
                  data-plasmic-override={overrides.svg2}
                  className={classNames(projectcss.all, sty.svg2)}
                >
                  <Frame2Icon
                    className={classNames(projectcss.all, sty.svg__nPeCw)}
                    role={"img"}
                  />
                </div>

                <div
                  data-plasmic-name={"svg3"}
                  data-plasmic-override={overrides.svg3}
                  className={classNames(projectcss.all, sty.svg3)}
                >
                  <Frame3Icon
                    className={classNames(projectcss.all, sty.svg__jrPc)}
                    role={"img"}
                  />
                </div>
              </div>

              <div
                data-plasmic-name={"shopifySecureBadgeLightShadowpng"}
                data-plasmic-override={
                  overrides.shopifySecureBadgeLightShadowpng
                }
                className={classNames(
                  projectcss.all,
                  sty.shopifySecureBadgeLightShadowpng
                )}
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  divshopifySectionFooter: [
    "divshopifySectionFooter",
    "div62",
    "footerLogopng",
    "div63",
    "div64",
    "div65",
    "company",
    "ul",
    "about",
    "press",
    "howItWorks",
    "contact",
    "brandAmbassador",
    "becomeASeller",
    "philosophy",
    "philanthropy",
    "helpFaQs",
    "div66",
    "products",
    "ul2",
    "rechargeable",
    "disposable",
    "giftCards",
    "div67",
    "legal",
    "ul3",
    "termsOfUse",
    "privacyPolicy",
    "shipping",
    "returnPolicy",
    "warranty",
    "div68",
    "div69",
    "followUs",
    "ul4",
    "svg2",
    "svg3",
    "shopifySecureBadgeLightShadowpng"
  ],
  div62: [
    "div62",
    "footerLogopng",
    "div63",
    "div64",
    "div65",
    "company",
    "ul",
    "about",
    "press",
    "howItWorks",
    "contact",
    "brandAmbassador",
    "becomeASeller",
    "philosophy",
    "philanthropy",
    "helpFaQs",
    "div66",
    "products",
    "ul2",
    "rechargeable",
    "disposable",
    "giftCards",
    "div67",
    "legal",
    "ul3",
    "termsOfUse",
    "privacyPolicy",
    "shipping",
    "returnPolicy",
    "warranty",
    "div68",
    "div69",
    "followUs",
    "ul4",
    "svg2",
    "svg3",
    "shopifySecureBadgeLightShadowpng"
  ],
  footerLogopng: ["footerLogopng"],
  div63: [
    "div63",
    "div64",
    "div65",
    "company",
    "ul",
    "about",
    "press",
    "howItWorks",
    "contact",
    "brandAmbassador",
    "becomeASeller",
    "philosophy",
    "philanthropy",
    "helpFaQs",
    "div66",
    "products",
    "ul2",
    "rechargeable",
    "disposable",
    "giftCards",
    "div67",
    "legal",
    "ul3",
    "termsOfUse",
    "privacyPolicy",
    "shipping",
    "returnPolicy",
    "warranty",
    "div68",
    "div69",
    "followUs",
    "ul4",
    "svg2",
    "svg3",
    "shopifySecureBadgeLightShadowpng"
  ],
  div64: [
    "div64",
    "div65",
    "company",
    "ul",
    "about",
    "press",
    "howItWorks",
    "contact",
    "brandAmbassador",
    "becomeASeller",
    "philosophy",
    "philanthropy",
    "helpFaQs",
    "div66",
    "products",
    "ul2",
    "rechargeable",
    "disposable",
    "giftCards",
    "div67",
    "legal",
    "ul3",
    "termsOfUse",
    "privacyPolicy",
    "shipping",
    "returnPolicy",
    "warranty"
  ],
  div65: [
    "div65",
    "company",
    "ul",
    "about",
    "press",
    "howItWorks",
    "contact",
    "brandAmbassador",
    "becomeASeller",
    "philosophy",
    "philanthropy",
    "helpFaQs"
  ],
  company: ["company"],
  ul: [
    "ul",
    "about",
    "press",
    "howItWorks",
    "contact",
    "brandAmbassador",
    "becomeASeller",
    "philosophy",
    "philanthropy",
    "helpFaQs"
  ],
  about: ["about"],
  press: ["press"],
  howItWorks: ["howItWorks"],
  contact: ["contact"],
  brandAmbassador: ["brandAmbassador"],
  becomeASeller: ["becomeASeller"],
  philosophy: ["philosophy"],
  philanthropy: ["philanthropy"],
  helpFaQs: ["helpFaQs"],
  div66: [
    "div66",
    "products",
    "ul2",
    "rechargeable",
    "disposable",
    "giftCards"
  ],
  products: ["products"],
  ul2: ["ul2", "rechargeable", "disposable", "giftCards"],
  rechargeable: ["rechargeable"],
  disposable: ["disposable"],
  giftCards: ["giftCards"],
  div67: [
    "div67",
    "legal",
    "ul3",
    "termsOfUse",
    "privacyPolicy",
    "shipping",
    "returnPolicy",
    "warranty"
  ],
  legal: ["legal"],
  ul3: [
    "ul3",
    "termsOfUse",
    "privacyPolicy",
    "shipping",
    "returnPolicy",
    "warranty"
  ],
  termsOfUse: ["termsOfUse"],
  privacyPolicy: ["privacyPolicy"],
  shipping: ["shipping"],
  returnPolicy: ["returnPolicy"],
  warranty: ["warranty"],
  div68: [
    "div68",
    "div69",
    "followUs",
    "ul4",
    "svg2",
    "svg3",
    "shopifySecureBadgeLightShadowpng"
  ],
  div69: [
    "div69",
    "followUs",
    "ul4",
    "svg2",
    "svg3",
    "shopifySecureBadgeLightShadowpng"
  ],
  followUs: ["followUs"],
  ul4: ["ul4", "svg2", "svg3"],
  svg2: ["svg2"],
  svg3: ["svg3"],
  shopifySecureBadgeLightShadowpng: ["shopifySecureBadgeLightShadowpng"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  divshopifySectionFooter: "div";
  div62: "div";
  footerLogopng: "a";
  div63: "div";
  div64: "div";
  div65: "div";
  company: "div";
  ul: "div";
  about: "div";
  press: "div";
  howItWorks: "div";
  contact: "div";
  brandAmbassador: "div";
  becomeASeller: "div";
  philosophy: "div";
  philanthropy: "div";
  helpFaQs: "div";
  div66: "div";
  products: "div";
  ul2: "div";
  rechargeable: "div";
  disposable: "div";
  giftCards: "div";
  div67: "div";
  legal: "div";
  ul3: "div";
  termsOfUse: "div";
  privacyPolicy: "div";
  shipping: "div";
  returnPolicy: "div";
  warranty: "div";
  div68: "div";
  div69: "div";
  followUs: "div";
  ul4: "div";
  svg2: "div";
  svg3: "div";
  shopifySecureBadgeLightShadowpng: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFooter414Px__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFooter414Px__VariantsArgs;
    args?: PlasmicFooter414Px__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFooter414Px__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicFooter414Px__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicFooter414Px__ArgProps,
          internalVariantPropNames: PlasmicFooter414Px__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFooter414Px__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "divshopifySectionFooter") {
    func.displayName = "PlasmicFooter414Px";
  } else {
    func.displayName = `PlasmicFooter414Px.${nodeName}`;
  }
  return func;
}

export const PlasmicFooter414Px = Object.assign(
  // Top-level PlasmicFooter414Px renders the root element
  makeNodeComponent("divshopifySectionFooter"),
  {
    // Helper components rendering sub-elements
    div62: makeNodeComponent("div62"),
    footerLogopng: makeNodeComponent("footerLogopng"),
    div63: makeNodeComponent("div63"),
    div64: makeNodeComponent("div64"),
    div65: makeNodeComponent("div65"),
    company: makeNodeComponent("company"),
    ul: makeNodeComponent("ul"),
    about: makeNodeComponent("about"),
    press: makeNodeComponent("press"),
    howItWorks: makeNodeComponent("howItWorks"),
    contact: makeNodeComponent("contact"),
    brandAmbassador: makeNodeComponent("brandAmbassador"),
    becomeASeller: makeNodeComponent("becomeASeller"),
    philosophy: makeNodeComponent("philosophy"),
    philanthropy: makeNodeComponent("philanthropy"),
    helpFaQs: makeNodeComponent("helpFaQs"),
    div66: makeNodeComponent("div66"),
    products: makeNodeComponent("products"),
    ul2: makeNodeComponent("ul2"),
    rechargeable: makeNodeComponent("rechargeable"),
    disposable: makeNodeComponent("disposable"),
    giftCards: makeNodeComponent("giftCards"),
    div67: makeNodeComponent("div67"),
    legal: makeNodeComponent("legal"),
    ul3: makeNodeComponent("ul3"),
    termsOfUse: makeNodeComponent("termsOfUse"),
    privacyPolicy: makeNodeComponent("privacyPolicy"),
    shipping: makeNodeComponent("shipping"),
    returnPolicy: makeNodeComponent("returnPolicy"),
    warranty: makeNodeComponent("warranty"),
    div68: makeNodeComponent("div68"),
    div69: makeNodeComponent("div69"),
    followUs: makeNodeComponent("followUs"),
    ul4: makeNodeComponent("ul4"),
    svg2: makeNodeComponent("svg2"),
    svg3: makeNodeComponent("svg3"),
    shopifySecureBadgeLightShadowpng: makeNodeComponent(
      "shopifySecureBadgeLightShadowpng"
    ),

    // Metadata about props expected for PlasmicFooter414Px
    internalVariantProps: PlasmicFooter414Px__VariantProps,
    internalArgProps: PlasmicFooter414Px__ArgProps
  }
);

export default PlasmicFooter414Px;
/* prettier-ignore-end */
