// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wJD4VsJTYW6gZPn3AUEzqs
// Component: -iDh_LbE9_cuN
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantssuXxHpH6GpmS } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: SUXxHpH6GpmS/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_masteri_sparq.module.css"; // plasmic-import: wJD4VsJTYW6gZPn3AUEzqs/projectcss
import sty from "./PlasmicVariety6Pack1440Px.module.css"; // plasmic-import: -iDh_LbE9_cuN/css

export type PlasmicVariety6Pack1440Px__VariantMembers = {};
export type PlasmicVariety6Pack1440Px__VariantsArgs = {};
type VariantPropType = keyof PlasmicVariety6Pack1440Px__VariantsArgs;
export const PlasmicVariety6Pack1440Px__VariantProps =
  new Array<VariantPropType>();

export type PlasmicVariety6Pack1440Px__ArgsType = {};
type ArgPropType = keyof PlasmicVariety6Pack1440Px__ArgsType;
export const PlasmicVariety6Pack1440Px__ArgProps = new Array<ArgPropType>();

export type PlasmicVariety6Pack1440Px__OverridesType = {
  div110?: p.Flex<"div">;
  a12?: p.Flex<"div">;
  productVariety1C2E7Bd9Ac9C4989Bfad811526Dad7E0250X2502Xjpg2?: p.Flex<"a"> &
    Partial<LinkProps>;
  div111?: p.Flex<"div">;
  _43Rating447Votes9?: p.Flex<"div">;
  i41?: p.Flex<"div">;
  i42?: p.Flex<"div">;
  i43?: p.Flex<"div">;
  i44?: p.Flex<"div">;
  i45?: p.Flex<"div">;
  div112?: p.Flex<"a"> & Partial<LinkProps>;
  span7?: p.Flex<"div">;
  bestSeller2?: p.Flex<"div">;
  form9?: p.Flex<"div">;
  div113?: p.Flex<"div">;
  div114?: p.Flex<"div">;
  div115?: p.Flex<"div">;
  div116?: p.Flex<"a"> & Partial<LinkProps>;
  label17?: p.Flex<"div">;
  strawberry9?: p.Flex<"div">;
  div117?: p.Flex<"a"> & Partial<LinkProps>;
  label18?: p.Flex<"div">;
  vanilla9?: p.Flex<"div">;
  div118?: p.Flex<"div">;
  buttonAddToCart43324944548532?: p.Flex<"a"> & Partial<LinkProps>;
};

export interface DefaultVariety6Pack1440PxProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicVariety6Pack1440Px__RenderFunc(props: {
  variants: PlasmicVariety6Pack1440Px__VariantsArgs;
  args: PlasmicVariety6Pack1440Px__ArgsType;
  overrides: PlasmicVariety6Pack1440Px__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantssuXxHpH6GpmS()
  });

  return (
    <div
      data-plasmic-name={"div110"}
      data-plasmic-override={overrides.div110}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.div110
      )}
    >
      <div
        data-plasmic-name={"a12"}
        data-plasmic-override={overrides.a12}
        className={classNames(projectcss.all, sty.a12)}
      >
        <p.PlasmicLink
          data-plasmic-name={
            "productVariety1C2E7Bd9Ac9C4989Bfad811526Dad7E0250X2502Xjpg2"
          }
          data-plasmic-override={
            overrides.productVariety1C2E7Bd9Ac9C4989Bfad811526Dad7E0250X2502Xjpg2
          }
          className={classNames(
            projectcss.all,
            projectcss.a,
            sty.productVariety1C2E7Bd9Ac9C4989Bfad811526Dad7E0250X2502Xjpg2
          )}
          component={Link}
          href={
            "https://shop.lifehacksplus.com/discount/QUIT15?redirect=/collections/all/products/3-pack?variant=31099464122437" as const
          }
          platform={"nextjs"}
        />

        <div
          data-plasmic-name={"div111"}
          data-plasmic-override={overrides.div111}
          className={classNames(projectcss.all, sty.div111)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__xgMR
            )}
          >
            {"Vitamin Air 3-Pack"}
          </div>

          <div
            data-plasmic-name={"_43Rating447Votes9"}
            data-plasmic-override={overrides._43Rating447Votes9}
            className={classNames(projectcss.all, sty._43Rating447Votes9)}
          >
            <div
              data-plasmic-name={"i41"}
              data-plasmic-override={overrides.i41}
              className={classNames(projectcss.all, sty.i41)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qw6H9
                )}
              >
                {"★\t"}
              </div>
            </div>

            <div
              data-plasmic-name={"i42"}
              data-plasmic-override={overrides.i42}
              className={classNames(projectcss.all, sty.i42)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pnegH
                )}
              >
                {"★\t"}
              </div>
            </div>

            <div
              data-plasmic-name={"i43"}
              data-plasmic-override={overrides.i43}
              className={classNames(projectcss.all, sty.i43)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__yxguq
                )}
              >
                {"★\t"}
              </div>
            </div>

            <div
              data-plasmic-name={"i44"}
              data-plasmic-override={overrides.i44}
              className={classNames(projectcss.all, sty.i44)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__scjQn
                )}
              >
                {"★\t"}
              </div>
            </div>

            <div
              data-plasmic-name={"i45"}
              data-plasmic-override={overrides.i45}
              className={classNames(projectcss.all, sty.i45)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fyM60
                )}
              >
                {"★\t"}
              </div>
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__qBEym
              )}
            >
              {"(447)"}
            </div>
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__puzg6
            )}
          >
            {"$56"}
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__mf5Lp
            )}
          >
            {"(One of each formulation)"}
          </div>
        </div>

        <p.PlasmicLink
          data-plasmic-name={"div112"}
          data-plasmic-override={overrides.div112}
          className={classNames(projectcss.all, projectcss.a, sty.div112)}
          component={Link}
          href={
            "https://shop.lifehacksplus.com/discount/QUIT15?redirect=/collections/all/products/3-pack?variant=31099464122437" as const
          }
          platform={"nextjs"}
        >
          <div
            data-plasmic-name={"span7"}
            data-plasmic-override={overrides.span7}
            className={classNames(projectcss.all, sty.span7)}
          >
            <div
              data-plasmic-name={"bestSeller2"}
              data-plasmic-override={overrides.bestSeller2}
              className={classNames(projectcss.all, sty.bestSeller2)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__wUomj
              )}
            >
              {hasVariant(globalVariants, "screen", "desktopOnly")
                ? "BEST VALUE!"
                : "BEST SELLER!"}
            </div>
          </div>
        </p.PlasmicLink>
      </div>

      <div
        data-plasmic-name={"form9"}
        data-plasmic-override={overrides.form9}
        className={classNames(projectcss.all, sty.form9)}
      >
        <div
          data-plasmic-name={"div113"}
          data-plasmic-override={overrides.div113}
          className={classNames(projectcss.all, sty.div113)}
        >
          <p.Stack
            as={"div"}
            data-plasmic-name={"div114"}
            data-plasmic-override={overrides.div114}
            hasGap={true}
            className={classNames(projectcss.all, sty.div114)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__p1YkE
              )}
            >
              {"Choose Flavor"}
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"div115"}
              data-plasmic-override={overrides.div115}
              hasGap={true}
              className={classNames(projectcss.all, sty.div115)}
            >
              <p.PlasmicLink
                data-plasmic-name={"div116"}
                data-plasmic-override={overrides.div116}
                className={classNames(projectcss.all, projectcss.a, sty.div116)}
                component={Link}
                href={
                  "https://shop.lifehacksplus.com/discount/QUIT15?redirect=/collections/all/products/3-pack?variant=31099464122437" as const
                }
                platform={"nextjs"}
              >
                <div
                  data-plasmic-name={"label17"}
                  data-plasmic-override={overrides.label17}
                  className={classNames(projectcss.all, sty.label17)}
                />

                <div
                  data-plasmic-name={"strawberry9"}
                  data-plasmic-override={overrides.strawberry9}
                  className={classNames(projectcss.all, sty.strawberry9)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qh3Sg
                    )}
                  >
                    {"Strawberry"}
                  </div>
                </div>
              </p.PlasmicLink>

              <p.PlasmicLink
                data-plasmic-name={"div117"}
                data-plasmic-override={overrides.div117}
                className={classNames(projectcss.all, projectcss.a, sty.div117)}
                component={Link}
                href={
                  "https://www.sparqlife.com/collections/all/products/3-pack?variant=31099464155205" as const
                }
                platform={"nextjs"}
              >
                <div
                  data-plasmic-name={"label18"}
                  data-plasmic-override={overrides.label18}
                  className={classNames(projectcss.all, sty.label18)}
                />

                <div
                  data-plasmic-name={"vanilla9"}
                  data-plasmic-override={overrides.vanilla9}
                  className={classNames(projectcss.all, sty.vanilla9)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__weLem
                    )}
                  >
                    {"Vanilla"}
                  </div>
                </div>
              </p.PlasmicLink>
            </p.Stack>
          </p.Stack>
        </div>

        <div
          data-plasmic-name={"div118"}
          data-plasmic-override={overrides.div118}
          className={classNames(projectcss.all, sty.div118)}
        >
          <p.PlasmicLink
            data-plasmic-name={"buttonAddToCart43324944548532"}
            data-plasmic-override={overrides.buttonAddToCart43324944548532}
            className={classNames(
              projectcss.all,
              projectcss.a,
              sty.buttonAddToCart43324944548532
            )}
            component={Link}
            href={
              "https://shop.lifehacksplus.com/discount/QUIT15?redirect=/collections/all/products/3-pack?variant=31099464122437" as const
            }
            platform={"nextjs"}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___1VpWg
              )}
            >
              {"SHOP NOW"}
            </div>
          </p.PlasmicLink>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  div110: [
    "div110",
    "a12",
    "productVariety1C2E7Bd9Ac9C4989Bfad811526Dad7E0250X2502Xjpg2",
    "div111",
    "_43Rating447Votes9",
    "i41",
    "i42",
    "i43",
    "i44",
    "i45",
    "div112",
    "span7",
    "bestSeller2",
    "form9",
    "div113",
    "div114",
    "div115",
    "div116",
    "label17",
    "strawberry9",
    "div117",
    "label18",
    "vanilla9",
    "div118",
    "buttonAddToCart43324944548532"
  ],
  a12: [
    "a12",
    "productVariety1C2E7Bd9Ac9C4989Bfad811526Dad7E0250X2502Xjpg2",
    "div111",
    "_43Rating447Votes9",
    "i41",
    "i42",
    "i43",
    "i44",
    "i45",
    "div112",
    "span7",
    "bestSeller2"
  ],
  productVariety1C2E7Bd9Ac9C4989Bfad811526Dad7E0250X2502Xjpg2: [
    "productVariety1C2E7Bd9Ac9C4989Bfad811526Dad7E0250X2502Xjpg2"
  ],
  div111: ["div111", "_43Rating447Votes9", "i41", "i42", "i43", "i44", "i45"],
  _43Rating447Votes9: ["_43Rating447Votes9", "i41", "i42", "i43", "i44", "i45"],
  i41: ["i41"],
  i42: ["i42"],
  i43: ["i43"],
  i44: ["i44"],
  i45: ["i45"],
  div112: ["div112", "span7", "bestSeller2"],
  span7: ["span7", "bestSeller2"],
  bestSeller2: ["bestSeller2"],
  form9: [
    "form9",
    "div113",
    "div114",
    "div115",
    "div116",
    "label17",
    "strawberry9",
    "div117",
    "label18",
    "vanilla9",
    "div118",
    "buttonAddToCart43324944548532"
  ],
  div113: [
    "div113",
    "div114",
    "div115",
    "div116",
    "label17",
    "strawberry9",
    "div117",
    "label18",
    "vanilla9"
  ],
  div114: [
    "div114",
    "div115",
    "div116",
    "label17",
    "strawberry9",
    "div117",
    "label18",
    "vanilla9"
  ],
  div115: [
    "div115",
    "div116",
    "label17",
    "strawberry9",
    "div117",
    "label18",
    "vanilla9"
  ],
  div116: ["div116", "label17", "strawberry9"],
  label17: ["label17"],
  strawberry9: ["strawberry9"],
  div117: ["div117", "label18", "vanilla9"],
  label18: ["label18"],
  vanilla9: ["vanilla9"],
  div118: ["div118", "buttonAddToCart43324944548532"],
  buttonAddToCart43324944548532: ["buttonAddToCart43324944548532"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  div110: "div";
  a12: "div";
  productVariety1C2E7Bd9Ac9C4989Bfad811526Dad7E0250X2502Xjpg2: "a";
  div111: "div";
  _43Rating447Votes9: "div";
  i41: "div";
  i42: "div";
  i43: "div";
  i44: "div";
  i45: "div";
  div112: "a";
  span7: "div";
  bestSeller2: "div";
  form9: "div";
  div113: "div";
  div114: "div";
  div115: "div";
  div116: "a";
  label17: "div";
  strawberry9: "div";
  div117: "a";
  label18: "div";
  vanilla9: "div";
  div118: "div";
  buttonAddToCart43324944548532: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicVariety6Pack1440Px__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicVariety6Pack1440Px__VariantsArgs;
    args?: PlasmicVariety6Pack1440Px__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicVariety6Pack1440Px__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicVariety6Pack1440Px__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicVariety6Pack1440Px__ArgProps,
          internalVariantPropNames: PlasmicVariety6Pack1440Px__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicVariety6Pack1440Px__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "div110") {
    func.displayName = "PlasmicVariety6Pack1440Px";
  } else {
    func.displayName = `PlasmicVariety6Pack1440Px.${nodeName}`;
  }
  return func;
}

export const PlasmicVariety6Pack1440Px = Object.assign(
  // Top-level PlasmicVariety6Pack1440Px renders the root element
  makeNodeComponent("div110"),
  {
    // Helper components rendering sub-elements
    a12: makeNodeComponent("a12"),
    productVariety1C2E7Bd9Ac9C4989Bfad811526Dad7E0250X2502Xjpg2:
      makeNodeComponent(
        "productVariety1C2E7Bd9Ac9C4989Bfad811526Dad7E0250X2502Xjpg2"
      ),
    div111: makeNodeComponent("div111"),
    _43Rating447Votes9: makeNodeComponent("_43Rating447Votes9"),
    i41: makeNodeComponent("i41"),
    i42: makeNodeComponent("i42"),
    i43: makeNodeComponent("i43"),
    i44: makeNodeComponent("i44"),
    i45: makeNodeComponent("i45"),
    div112: makeNodeComponent("div112"),
    span7: makeNodeComponent("span7"),
    bestSeller2: makeNodeComponent("bestSeller2"),
    form9: makeNodeComponent("form9"),
    div113: makeNodeComponent("div113"),
    div114: makeNodeComponent("div114"),
    div115: makeNodeComponent("div115"),
    div116: makeNodeComponent("div116"),
    label17: makeNodeComponent("label17"),
    strawberry9: makeNodeComponent("strawberry9"),
    div117: makeNodeComponent("div117"),
    label18: makeNodeComponent("label18"),
    vanilla9: makeNodeComponent("vanilla9"),
    div118: makeNodeComponent("div118"),
    buttonAddToCart43324944548532: makeNodeComponent(
      "buttonAddToCart43324944548532"
    ),

    // Metadata about props expected for PlasmicVariety6Pack1440Px
    internalVariantProps: PlasmicVariety6Pack1440Px__VariantProps,
    internalArgProps: PlasmicVariety6Pack1440Px__ArgProps
  }
);

export default PlasmicVariety6Pack1440Px;
/* prettier-ignore-end */
