// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wJD4VsJTYW6gZPn3AUEzqs
// Component: 7yDDnDCshHrNn
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_masteri_sparq.module.css"; // plasmic-import: wJD4VsJTYW6gZPn3AUEzqs/projectcss
import sty from "./PlasmicHeadlineIcons1440Px.module.css"; // plasmic-import: 7yDDnDCshHrNn/css

export type PlasmicHeadlineIcons1440Px__VariantMembers = {};
export type PlasmicHeadlineIcons1440Px__VariantsArgs = {};
type VariantPropType = keyof PlasmicHeadlineIcons1440Px__VariantsArgs;
export const PlasmicHeadlineIcons1440Px__VariantProps =
  new Array<VariantPropType>();

export type PlasmicHeadlineIcons1440Px__ArgsType = {};
type ArgPropType = keyof PlasmicHeadlineIcons1440Px__ArgsType;
export const PlasmicHeadlineIcons1440Px__ArgProps = new Array<ArgPropType>();

export type PlasmicHeadlineIcons1440Px__OverridesType = {
  div77?: p.Flex<"div">;
  breatheVitaminAir2?: p.Flex<"div">;
  div78?: p.Flex<"div">;
  div79?: p.Flex<"div">;
  smokingIconAc8544Ef2A784A929740Ba3C7312E5C5480X480Png2?: p.Flex<"div">;
  _0Nicotine2?: p.Flex<"div">;
  div80?: p.Flex<"div">;
  beakerIcon09Efe31CB2E44C7F8A8FF564E86Fe6E1480X480Png2?: p.Flex<"div">;
  labTested2?: p.Flex<"div">;
  div81?: p.Flex<"div">;
  pillsIcon73726148C05B472793782519623Fd4A0480X480Png2?: p.Flex<"div">;
  vitamins2?: p.Flex<"div">;
  div82?: p.Flex<"div">;
  recycleIcon1607Fa063A4B4D0BA0A61Cd803B18C85480X480Png2?: p.Flex<"div">;
  recyclable2?: p.Flex<"div">;
};

export interface DefaultHeadlineIcons1440PxProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHeadlineIcons1440Px__RenderFunc(props: {
  variants: PlasmicHeadlineIcons1440Px__VariantsArgs;
  args: PlasmicHeadlineIcons1440Px__ArgsType;
  overrides: PlasmicHeadlineIcons1440Px__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  return (
    <div
      data-plasmic-name={"div77"}
      data-plasmic-override={overrides.div77}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.div77
      )}
    >
      <div
        data-plasmic-name={"breatheVitaminAir2"}
        data-plasmic-override={overrides.breatheVitaminAir2}
        className={classNames(projectcss.all, sty.breatheVitaminAir2)}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___1Okji
          )}
        >
          {"BREATHE VITAMIN AIR®"}
        </div>
      </div>

      <div
        data-plasmic-name={"div78"}
        data-plasmic-override={overrides.div78}
        className={classNames(projectcss.all, sty.div78)}
      >
        <div
          data-plasmic-name={"div79"}
          data-plasmic-override={overrides.div79}
          className={classNames(projectcss.all, sty.div79)}
        >
          <div
            data-plasmic-name={
              "smokingIconAc8544Ef2A784A929740Ba3C7312E5C5480X480Png2"
            }
            data-plasmic-override={
              overrides.smokingIconAc8544Ef2A784A929740Ba3C7312E5C5480X480Png2
            }
            className={classNames(
              projectcss.all,
              sty.smokingIconAc8544Ef2A784A929740Ba3C7312E5C5480X480Png2
            )}
          />

          <div
            data-plasmic-name={"_0Nicotine2"}
            data-plasmic-override={overrides._0Nicotine2}
            className={classNames(projectcss.all, sty._0Nicotine2)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__cHceg
              )}
            >
              {"0% Nicotine"}
            </div>
          </div>
        </div>

        <div
          data-plasmic-name={"div80"}
          data-plasmic-override={overrides.div80}
          className={classNames(projectcss.all, sty.div80)}
        >
          <div
            data-plasmic-name={
              "beakerIcon09Efe31CB2E44C7F8A8FF564E86Fe6E1480X480Png2"
            }
            data-plasmic-override={
              overrides.beakerIcon09Efe31CB2E44C7F8A8FF564E86Fe6E1480X480Png2
            }
            className={classNames(
              projectcss.all,
              sty.beakerIcon09Efe31Cb2E44C7F8A8Ff564E86Fe6E1480X480Png2
            )}
          />

          <div
            data-plasmic-name={"labTested2"}
            data-plasmic-override={overrides.labTested2}
            className={classNames(projectcss.all, sty.labTested2)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___3DhZc
              )}
            >
              {"Lab-Tested"}
            </div>
          </div>
        </div>

        <div
          data-plasmic-name={"div81"}
          data-plasmic-override={overrides.div81}
          className={classNames(projectcss.all, sty.div81)}
        >
          <div
            data-plasmic-name={
              "pillsIcon73726148C05B472793782519623Fd4A0480X480Png2"
            }
            data-plasmic-override={
              overrides.pillsIcon73726148C05B472793782519623Fd4A0480X480Png2
            }
            className={classNames(
              projectcss.all,
              sty.pillsIcon73726148C05B472793782519623Fd4A0480X480Png2
            )}
          />

          <div
            data-plasmic-name={"vitamins2"}
            data-plasmic-override={overrides.vitamins2}
            className={classNames(projectcss.all, sty.vitamins2)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__vkGa1
              )}
            >
              {"Vitamins"}
            </div>
          </div>
        </div>

        <div
          data-plasmic-name={"div82"}
          data-plasmic-override={overrides.div82}
          className={classNames(projectcss.all, sty.div82)}
        >
          <div
            data-plasmic-name={
              "recycleIcon1607Fa063A4B4D0BA0A61Cd803B18C85480X480Png2"
            }
            data-plasmic-override={
              overrides.recycleIcon1607Fa063A4B4D0BA0A61Cd803B18C85480X480Png2
            }
            className={classNames(
              projectcss.all,
              sty.recycleIcon1607Fa063A4B4D0Ba0A61Cd803B18C85480X480Png2
            )}
          />

          <div
            data-plasmic-name={"recyclable2"}
            data-plasmic-override={overrides.recyclable2}
            className={classNames(projectcss.all, sty.recyclable2)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__boLNm
              )}
            >
              {"Recyclable"}
            </div>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  div77: [
    "div77",
    "breatheVitaminAir2",
    "div78",
    "div79",
    "smokingIconAc8544Ef2A784A929740Ba3C7312E5C5480X480Png2",
    "_0Nicotine2",
    "div80",
    "beakerIcon09Efe31CB2E44C7F8A8FF564E86Fe6E1480X480Png2",
    "labTested2",
    "div81",
    "pillsIcon73726148C05B472793782519623Fd4A0480X480Png2",
    "vitamins2",
    "div82",
    "recycleIcon1607Fa063A4B4D0BA0A61Cd803B18C85480X480Png2",
    "recyclable2"
  ],
  breatheVitaminAir2: ["breatheVitaminAir2"],
  div78: [
    "div78",
    "div79",
    "smokingIconAc8544Ef2A784A929740Ba3C7312E5C5480X480Png2",
    "_0Nicotine2",
    "div80",
    "beakerIcon09Efe31CB2E44C7F8A8FF564E86Fe6E1480X480Png2",
    "labTested2",
    "div81",
    "pillsIcon73726148C05B472793782519623Fd4A0480X480Png2",
    "vitamins2",
    "div82",
    "recycleIcon1607Fa063A4B4D0BA0A61Cd803B18C85480X480Png2",
    "recyclable2"
  ],
  div79: [
    "div79",
    "smokingIconAc8544Ef2A784A929740Ba3C7312E5C5480X480Png2",
    "_0Nicotine2"
  ],
  smokingIconAc8544Ef2A784A929740Ba3C7312E5C5480X480Png2: [
    "smokingIconAc8544Ef2A784A929740Ba3C7312E5C5480X480Png2"
  ],
  _0Nicotine2: ["_0Nicotine2"],
  div80: [
    "div80",
    "beakerIcon09Efe31CB2E44C7F8A8FF564E86Fe6E1480X480Png2",
    "labTested2"
  ],
  beakerIcon09Efe31CB2E44C7F8A8FF564E86Fe6E1480X480Png2: [
    "beakerIcon09Efe31CB2E44C7F8A8FF564E86Fe6E1480X480Png2"
  ],
  labTested2: ["labTested2"],
  div81: [
    "div81",
    "pillsIcon73726148C05B472793782519623Fd4A0480X480Png2",
    "vitamins2"
  ],
  pillsIcon73726148C05B472793782519623Fd4A0480X480Png2: [
    "pillsIcon73726148C05B472793782519623Fd4A0480X480Png2"
  ],
  vitamins2: ["vitamins2"],
  div82: [
    "div82",
    "recycleIcon1607Fa063A4B4D0BA0A61Cd803B18C85480X480Png2",
    "recyclable2"
  ],
  recycleIcon1607Fa063A4B4D0BA0A61Cd803B18C85480X480Png2: [
    "recycleIcon1607Fa063A4B4D0BA0A61Cd803B18C85480X480Png2"
  ],
  recyclable2: ["recyclable2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  div77: "div";
  breatheVitaminAir2: "div";
  div78: "div";
  div79: "div";
  smokingIconAc8544Ef2A784A929740Ba3C7312E5C5480X480Png2: "div";
  _0Nicotine2: "div";
  div80: "div";
  beakerIcon09Efe31CB2E44C7F8A8FF564E86Fe6E1480X480Png2: "div";
  labTested2: "div";
  div81: "div";
  pillsIcon73726148C05B472793782519623Fd4A0480X480Png2: "div";
  vitamins2: "div";
  div82: "div";
  recycleIcon1607Fa063A4B4D0BA0A61Cd803B18C85480X480Png2: "div";
  recyclable2: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHeadlineIcons1440Px__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHeadlineIcons1440Px__VariantsArgs;
    args?: PlasmicHeadlineIcons1440Px__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHeadlineIcons1440Px__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHeadlineIcons1440Px__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHeadlineIcons1440Px__ArgProps,
          internalVariantPropNames: PlasmicHeadlineIcons1440Px__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHeadlineIcons1440Px__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "div77") {
    func.displayName = "PlasmicHeadlineIcons1440Px";
  } else {
    func.displayName = `PlasmicHeadlineIcons1440Px.${nodeName}`;
  }
  return func;
}

export const PlasmicHeadlineIcons1440Px = Object.assign(
  // Top-level PlasmicHeadlineIcons1440Px renders the root element
  makeNodeComponent("div77"),
  {
    // Helper components rendering sub-elements
    breatheVitaminAir2: makeNodeComponent("breatheVitaminAir2"),
    div78: makeNodeComponent("div78"),
    div79: makeNodeComponent("div79"),
    smokingIconAc8544Ef2A784A929740Ba3C7312E5C5480X480Png2: makeNodeComponent(
      "smokingIconAc8544Ef2A784A929740Ba3C7312E5C5480X480Png2"
    ),
    _0Nicotine2: makeNodeComponent("_0Nicotine2"),
    div80: makeNodeComponent("div80"),
    beakerIcon09Efe31CB2E44C7F8A8FF564E86Fe6E1480X480Png2: makeNodeComponent(
      "beakerIcon09Efe31CB2E44C7F8A8FF564E86Fe6E1480X480Png2"
    ),
    labTested2: makeNodeComponent("labTested2"),
    div81: makeNodeComponent("div81"),
    pillsIcon73726148C05B472793782519623Fd4A0480X480Png2: makeNodeComponent(
      "pillsIcon73726148C05B472793782519623Fd4A0480X480Png2"
    ),
    vitamins2: makeNodeComponent("vitamins2"),
    div82: makeNodeComponent("div82"),
    recycleIcon1607Fa063A4B4D0BA0A61Cd803B18C85480X480Png2: makeNodeComponent(
      "recycleIcon1607Fa063A4B4D0BA0A61Cd803B18C85480X480Png2"
    ),
    recyclable2: makeNodeComponent("recyclable2"),

    // Metadata about props expected for PlasmicHeadlineIcons1440Px
    internalVariantProps: PlasmicHeadlineIcons1440Px__VariantProps,
    internalArgProps: PlasmicHeadlineIcons1440Px__ArgProps
  }
);

export default PlasmicHeadlineIcons1440Px;
/* prettier-ignore-end */
